### PR TITLE
Fixes #7 - application of retention for tenant databases in HANA

### LINKED ISSUE #7: [sap-hana] Retention not applied to tenant databases
**Describe the bug**
When using these scripts to quiesce SAP HANA instances, the configured retention is not applied to the tenant database(s). It is only applied to `SYSTEMDB`. I have an idea how to fix it - will submit PR for further discussion.

**To Reproduce**
1. Configure backup of a HANA 2.0 instance with the pre/post scripts
2. Review present restore points in HANA Studio or VBR after the specified number of days

**Expected behavior**
It is expected that database backup retention is applied to both `SYSTEMDB` and the corresponding tenant database(s) on the instance.

**System information:**
 - OS: RHEL 7.6 (Linux 3.10.0-957.e17.x86_64)
 - HANA instance version 2.00.045.00.1575639312
 - HANA Studio version 2.3.47
 - Veeam Backup & Replication 10.0.1

### PR DESCRIPTION
**Pull request by poulpreben**
## Description

This change is fixes Issue #7. It is probably not the cleanest way to implement the fix, since it generates a command line such that includes two database entries i.e. `-d SYSTEMDB -d TENANTDB`, where the `TENANTDB` takes precedence. It was tricky to get full access to a test instance, so all input is much welcome.

### Type of change

* [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

It has been tested on a single instances of HANA 2.0.

### Checklist (check all applicable):

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in _hard to understand_ areas
* [ ] I have made corresponding changes to the documentation
* [ ] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tsightler** [comment]
I had worked on this a few months ago and felt like during testing that this didn't wasn't enough in the case where there were multiple tenant databases.  Was I wrong about that?  It seemed like, to do it correctly, I needed to loop through each tenant database but, when I started on that, it seemed to open up other requirements for tenant specific permissions and I started believing I'd need to refactor and I wasn't sure anyone was really using this code anyway since it was written prior to Veeam having official support for HANA.

I'm not super concerned about elegance as I would say this code is the opposite of that already.  I'm actually a little embarrassed that someone looked at it enough to figure out how to modify it!

**Comment by poulpreben** [comment]
I think that you are looping over all tenant databases (service) in [this line](https://github.com/VeeamHub/applications/pull/8/files#diff-532de713755f2b52986f2c517b0c7b6bR263). I did move the extraction of the database name over the section in which the SQL statements are generated, so that might have done the trick.

I will check and see if we have an instance available with more than a single tenant database. Most of them are upgraded from HANA 1.x, and I believe there has not been much consolidation since.

**Comment by poulpreben** [comment]
I have confirmed your research. The `sapservices` file does not include anything but the default tenant database name. In order to detect all running instances on the server, one of the approaches described [in this article](https://answers.sap.com/questions/271796/how-to-get-the-list-of-hana-instances-on-a-machine.html) must be used.

The reason we are still using the scripts is that the customer never deployed HANA Cockpit, which seems like the only place to configure retention settings for BACKINT backups. Currently, there are > 180,000 entries in the catalog for each tenant database (and Veeam) since they never get cleaned up.

I am currently installing HANA Express to see if I can figure out a solution to this. We are also pushing the customer to setup Cockpit in parallel. Until I have come up with a better solution, I am closing this PR.

**Comment by tsightler** [comment]
At least that means I wasn't wrong about the approach.  To be fair, until the most recent HANA2 SPS04 release I don't think you could snapshot HANA instances with multiple tenants, that's a really new feature overall.  Previously you could snapshot a multi-tenant database only if it had a single tenant, so your fix could be useful as a stop gap.

More recently I've had demand for implementing this script for customers that are moving to multi-tenant.  Apparently it's still popular for cases where customers want to take snapshot based backups (either storage based or VM based) to use for quicker DR scenarios or replication.  I guess I'll have to put fixing this back on my list.

**Pull request closed without merging**
